services:
  - type: web
    name: rastreador-caiaques-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
