services:
  - type: web
    name: rastreador-caiaques-backend
    runtime: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
